version: '3.8'

services:
  api:
    build:
      context: api
    entrypoint: /django/script.sh
    volumes:
      - static_files:/django/static
    ports:
      - 8000:8000

  www:
    build:
      context: www
      args:
        - API_URL=${API_URL}

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - www

volumes:
  static_files: null
