version: '3.8'

services:
  backend:
    build:
      context: backend
    entrypoint: /django/script.sh
    # volumes:
    #   - static_files:/django/static
    ports:
      - 8000:8000

  frontend:
    build:
      context: frontend
      args:
        - API_URL=${API_URL}
    ports:
      - 3000:80

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend

# volumes:
#   static_files: null
