# Generated by Django 3.2.4 on 2021-06-14 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drives.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(blank=True, default=drives.models.logged_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
