# Generated by Django 3.2.4 on 2021-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_auto_20210615_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='author',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
