# Generated by Django 3.2.4 on 2021-06-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20210615_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
