# Generated by Django 3.2.4 on 2021-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_auto_20210625_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
