# Generated by Django 3.2.4 on 2021-06-26 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0005_folder_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
