# Generated by Django 3.2.4 on 2021-06-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0006_auto_20210627_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
